name: Pull down code and run the master bash script

on: [push, pull_request]

jobs:
  run-fortran-moon-calculations:
    name: Run fortran moon calculations
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '2.7'

      - name: Install numPy
        run: pip install numpy

      - name: Run the master bash script
        run: |
          set +x
          chmod +x run.sh
          ./run.sh BDir2